### ISSUE TITLE
Accept lists of URIs

### ISSUE THREAD

**Issue by JulienPalard** [michelin/ChopChop#2]
Thanks for opening ChopChop!

Looked at `chopchop.yml` and though « I'll gladly add some... », but wanted to do it like so:
```yaml
- uri: ["/db.sql", "/db.sql.gz", "/db.sqlite", "/db.sqlite.gz", "/db.sqlite3", "/db.sqlite3.gz", "/data.sql", "/data.sql.gz", "/users.sql", "/users.sql.gz", "/dump.sql", "/dump.sql.gz", "/mysqldump.sql", "/mysqldump.sql.gz", "/backup.sql", "/backup.sql.gz", "/db.backup", "/db.backup.gz", "/database.sql", "/database.sql.gz", "/db-data.sql", "/db-data.sql.gz", "/db_test.sql", "/db_test.sql.gz", "/db-test.sql", "/db-test.sql.gz"]
  checks:
    - name: Database file
      status_code: 200
      remediation: Delete this file
      description: Verifies a database dump is accessible.
      severity: "High"
```

(and I bet we could continue for hours adding to this list)

As you imagine, I don't want to copy/paste the name, status_code, remediation, description, and severity 26 times.

Doodling around the idea, it would be great to be able to express those as a « [genex](https://github.com/audreyt/regex-genex) », or something similar, something like:

    /(db|database|backup|mysqldump|dump|data).(sql|sqlite|sqlite3)(\.gz)?

**Comment by tfalamu** [comment]
Is this a good first issue?

**Comment by LeaksDev** [comment]
Status Code 200 will give you 90% false positives for database backups.
A valid fileheader would eliminate this problem.

**Comment by ghost** [comment]
> 
> 
> Thanks for opening ChopChop!
> 
> Looked at `chopchop.yml` and though « I'll gladly add some... », but wanted to do it like so:
> 
> ```yaml
> - uri: ["/db.sql", "/db.sql.gz", "/db.sqlite", "/db.sqlite.gz", "/db.sqlite3", "/db.sqlite3.gz", "/data.sql", "/data.sql.gz", "/users.sql", "/users.sql.gz", "/dump.sql", "/dump.sql.gz", "/mysqldump.sql", "/mysqldump.sql.gz", "/backup.sql", "/backup.sql.gz", "/db.backup", "/db.backup.gz", "/database.sql", "/database.sql.gz", "/db-data.sql", "/db-data.sql.gz", "/db_test.sql", "/db_test.sql.gz", "/db-test.sql", "/db-test.sql.gz"]
>   checks:
>     - name: Database file
>       status_code: 200
>       remediation: Delete this file
>       description: Verifies a database dump is accessible.
>       severity: "High"
> ```
> 
> (and I bet we could continue for hours adding to this list)
> 
> As you imagine, I don't want to copy/paste the name, status_code, remediation, description, and severity 26 times.
> 
> Doodling around the idea, it would be great to be able to express those as a « [genex](https://github.com/audreyt/regex-genex) », or something similar, something like:
> 
> ```
> /(db|database|backup|mysqldump|dump|data).(sql|sqlite|sqlite3)(\.gz)?
> ```

Status Code 200 will give you 90% false positives for database backups.
A valid fileheader would eliminate this problem.
Not tested tho:

```yaml
  - uri: "/backup.sql"
    checks:
      - name: SQL Backup
        match:
          - '{"status"'
        headers:
          - "Content-Type:application/sql"
        remediation: Delete it.
        description: Backupfile of your database. Sensitive informations like admin login could be readable.
        severity: "High"
```

**Comment by isontheline** [comment]
Bonjour @JulienPalard, jamais entendu parler de "genex" auparavant 👴, c'est génial !

I agree with Julien, list of URIs is needed in a lot of use cases.
Implementation of "genex" has also been implemented into Golang : https://github.com/alixaxel/genex

@PaulSec could I help to implement this feature inside ChopChop?

**Comment by PaulSec** [comment]
Definitely! Go for it and open a pull request. I will review it ASAP when I will be back from holidays!

**Comment by DloomPlz** [comment]
Same here ! I'll work on multi-threading and refactor of code in the mean time.

**Comment by PaulSec** [comment]
The problem is known in the library we are using, see: https://github.com/go-yaml/yaml/issues/100

Would you find acceptable that the `uri` parameter is treated as an array all the time? Eg.

```yaml
  - uri: "/phpinfo.php"
    checks:
      - name: PHPInfo
        match:
          - 'phpinfo()'
        remediation: Disable phpinfo() in PHP.ini
        description: Checks that the phpinfo() function is accessible
        severity: "Low"
        tested: true
```

Would become: 

```yaml
  - uri: ["/phpinfo.php"]
    checks:
      - name: PHPInfo
        match:
          - 'phpinfo()'
        remediation: Disable phpinfo() in PHP.ini
        description: Checks that the phpinfo() function is accessible
        severity: "Low"
        tested: true
```

In this case, we wouldn't have any issue in order to unmarshal the data and we could allow array of `uri`.
